import GlobalProvider from "@/components/application/GlobalProvider";
import ThemeProvider from "@/components/application/Admin/ThemeProvider";
import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from 'react-toastify';



const assistant = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.className} antialiased`}
      >
        <GlobalProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>
            <ToastContainer />
            {children}
          </ThemeProvider>
        </GlobalProvider>

      </body>
    </html>
  );
}
