import GlobalProvider from "@/components/application/GlobalProvider";
import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from 'react-toastify';



const assistant = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.className} antialiased`}
      >
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>

      </body>
    </html>
  );
}
